double dist(double* r_1, double* r_2);
double random_double(double min, double max);
void print_array(int n, int p, double** array);
double* sum_array(double* r_1, double* r_2);
double* sub_array(double* r_1, double* r_2);
double* mult_array(double* r_1, double lambda);
int* get_coordinates(double* r_star);
void copy_space(double*** old_space, double*** new_space);
double*** initiate_space();
double**** initiate_vector_field();
void free_space(double*** space);
double max(double a, double b);
double min(double a, double b);
int modulo(int i, int n);
double modulo_double(double i, double n);
double cube_intersect(double* rmin_1, double* rmax_1,double* rmin_2, double* rmax_2);
double**** gradient(double*** field);
double*** laplacian(double*** field);
double norm(double* vector);
void print_field(double*** field, FILE* field_file);
void write_parameters();
void write_data(FILE* fichier, double** r_stars, double** v_stars, double** a_stars, double* m_stars);
